### ISSUE TITLE
[Title]: No exported type for headerLevelTypes (H1, H2, …)

### ISSUE THREAD

**Issue by ilhan007** [SAP/ui5-webcomponents-ngx#97]
### **Feature Request Description**
Title: No exported type for headerLevelTypes (H1, H2, …)

### **Proposed Solution**
Export types that are available in @ui5/webcomponents/dsit/types and @ui5/webcomponents-fiori/dsit/types

**Comment by g-cheishvili** [comment]
I tested the Angular directive, without generated type(using the Title directly from the ui5) and found that language server struggles to understand that the `TitleLevel` contains those heading types and recognizes it as `any` on HTML side, on the typescript class side, it works as expected. So I think leaving the generated ones for now is better.
Hoping it's fixed in ng17

**Comment by ilhan007** [comment]
Hello @timogeib please consider the answer by Giorgi above

**Comment by timogeib** [comment]
@ilhan007 importing the TitleTypes woks fine. Thank you for clarification. Issue is resolved for me. :-)
